########################################
# Part 1 - Seven segment, LEDs, switches,
# buttons, coins, etc.
########################################
set_property IOSTANDARD LVCMOS18 [get_ports {an[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {an[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {an[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {an[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ca[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ca[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ca[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ca[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ca[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ca[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ca[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ld[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ld[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ld[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ld[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[0]}]
set_property PACKAGE_PIN U2 [get_ports {an[3]}]
set_property PACKAGE_PIN U4 [get_ports {an[2]}]
set_property PACKAGE_PIN V4 [get_ports {an[1]}]
set_property PACKAGE_PIN W4 [get_ports {an[0]}]
set_property PACKAGE_PIN W7 [get_ports {ca[6]}]
set_property PACKAGE_PIN W6 [get_ports {ca[5]}]
set_property PACKAGE_PIN U8 [get_ports {ca[4]}]
set_property PACKAGE_PIN V8 [get_ports {ca[3]}]
set_property PACKAGE_PIN U5 [get_ports {ca[2]}]
set_property PACKAGE_PIN V5 [get_ports {ca[1]}]
set_property PACKAGE_PIN U7 [get_ports {ca[0]}]
set_property PACKAGE_PIN U16 [get_ports {ld[3]}]
set_property PACKAGE_PIN E19 [get_ports {ld[2]}]
set_property PACKAGE_PIN U19 [get_ports {ld[1]}]
set_property PACKAGE_PIN V19 [get_ports {ld[0]}]
set_property PACKAGE_PIN V17 [get_ports {sw[3]}]
set_property PACKAGE_PIN V16 [get_ports {sw[2]}]
set_property PACKAGE_PIN W16 [get_ports {sw[1]}]
set_property PACKAGE_PIN W17 [get_ports {sw[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports clr]
set_property IOSTANDARD LVCMOS18 [get_ports dime]
set_property IOSTANDARD LVCMOS18 [get_ports err]
set_property IOSTANDARD LVCMOS18 [get_ports nickel]
set_property IOSTANDARD LVCMOS18 [get_ports quarter]
set_property PACKAGE_PIN W5  [get_ports clk]
set_property PACKAGE_PIN T18 [get_ports clr]
set_property PACKAGE_PIN U18 [get_ports dime]
set_property PACKAGE_PIN L1  [get_ports err]
set_property PACKAGE_PIN W19 [get_ports nickel]
set_property PACKAGE_PIN T17 [get_ports quarter]
########################################
# New - 1 Hz clock indicator on LED15
########################################
set_property IOSTANDARD LVCMOS18 [get_ports led15]
# Basys3 LD15 is on pin T2
set_property PACKAGE_PIN T2 [get_ports led15]
########################################
# New - OLED Pmod on JB (from demo)
# Only the physical SPI / control pins
# remain as top-level ports.
########################################
set_property IOSTANDARD LVCMOS18 [get_ports CS]
set_property IOSTANDARD LVCMOS18 [get_ports SDIN]
set_property IOSTANDARD LVCMOS18 [get_ports SCLK]
set_property IOSTANDARD LVCMOS18 [get_ports DC]
set_property IOSTANDARD LVCMOS18 [get_ports RES]
set_property IOSTANDARD LVCMOS18 [get_ports VBAT]
set_property IOSTANDARD LVCMOS18 [get_ports VDD]
set_property PACKAGE_PIN A14 [get_ports CS]
set_property PACKAGE_PIN A16 [get_ports SDIN]
set_property PACKAGE_PIN B16 [get_ports SCLK]
set_property PACKAGE_PIN A15 [get_ports DC]
set_property PACKAGE_PIN A17 [get_ports RES]
set_property PACKAGE_PIN C15 [get_ports VBAT]
set_property PACKAGE_PIN C16 [get_ports VDD]
